use super::super::super::Cartridge;

#[derive(Clone, Copy)]
enum PrgReadHandler {
    Mapper210,
    Mapper21,
    Mapper22,
    Mapper23,
    Vrc6,
    Vrc7,
    Mapper25,
    Mapper18,
    Namco163,
    Mmc5,
    Mapper64,
    Nrom,
    Mapper59,
    Mapper60,
    Mapper61,
    Mapper63,
    Mapper99,
    Mapper142,
    Axrom,
    Mmc3,
    Mapper37,
    Mapper44,
    Mapper32,
    Mapper40,
    Mapper42,
    Mapper43,
    Mapper47,
    TaitoTc0190,
    Namco108,
    Mapper114,
    Mapper115,
    Mapper123,
    Mapper205,
    Mmc1,
    Mapper208,
    Mapper15,
    Mapper221,
    Mapper225,
    Mapper230,
    Mapper227,
    Mapper231,
    Mapper236,
    Mapper232,
    Mapper233,
    Mapper234,
    Mapper235,
    Mapper246,
    Mapper200,
    Mapper202,
    Mapper212,
    Mapper226,
    Mapper228,
    Mapper242,
    Uxrom,
    Mapper50,
    Mapper58,
    Mapper65,
    Sunsoft3,
    Mapper229,
    UxromInverted,
    FixedLastSwitchHigh,
    Mapper103,
    Mapper191,
    Mapper245,
    Sunsoft4,
    Vrc1,
    TaitoX1005,
    TaitoX1017,
    Mmc2,
    Bandai,
    Fme7,
    Zero,
}

impl Cartridge {
    #[inline]
    pub fn read_prg(&self, addr: u16) -> u8 {
        let rom_addr = addr - 0x8000;
        if self.is_nrom() {
            return self.read_prg_nrom(rom_addr);
        }

        match self.prg_read_handler() {
            PrgReadHandler::Mapper210 => self.read_prg_mapper210(addr),
            PrgReadHandler::Mapper21 => self.read_prg_mapper21(addr),
            PrgReadHandler::Mapper22 => self.read_prg_mapper22(addr),
            PrgReadHandler::Mapper23 => self.read_prg_mapper23(addr),
            PrgReadHandler::Vrc6 => self.read_prg_vrc6(addr),
            PrgReadHandler::Vrc7 => self.read_prg_vrc7(addr),
            PrgReadHandler::Mapper25 => self.read_prg_mapper25(addr),
            PrgReadHandler::Mapper18 => self.read_prg_mapper18(addr),
            PrgReadHandler::Namco163 => self.read_prg_namco163(addr),
            PrgReadHandler::Mmc5 => self.read_prg_mmc5(addr),
            PrgReadHandler::Mapper64 => self.read_prg_mapper64(addr),
            PrgReadHandler::Nrom => self.read_prg_nrom(rom_addr),
            PrgReadHandler::Mapper59 => self.read_prg_mapper59(addr),
            PrgReadHandler::Mapper60 => self.read_prg_mapper60(addr),
            PrgReadHandler::Mapper61 => self.read_prg_mapper61(addr),
            PrgReadHandler::Mapper63 => self.read_prg_mapper63(addr),
            PrgReadHandler::Mapper99 => self.read_prg_mapper99(addr),
            PrgReadHandler::Mapper142 => self.read_prg_mapper142(addr),
            PrgReadHandler::Axrom => self.read_prg_axrom(addr),
            PrgReadHandler::Mmc3 => self.read_prg_mmc3(addr),
            PrgReadHandler::Mapper37 => self.read_prg_mapper37(addr),
            PrgReadHandler::Mapper44 => self.read_prg_mapper44(addr),
            PrgReadHandler::Mapper32 => self.read_prg_mapper32(addr),
            PrgReadHandler::Mapper40 => self.read_prg_mapper40(addr),
            PrgReadHandler::Mapper42 => self.read_prg_mapper42(addr),
            PrgReadHandler::Mapper43 => self.read_prg_mapper43(addr),
            PrgReadHandler::Mapper47 => self.read_prg_mapper47(addr),
            PrgReadHandler::TaitoTc0190 => self.read_prg_taito_tc0190(addr),
            PrgReadHandler::Namco108 => self.read_prg_namco108(addr),
            PrgReadHandler::Mapper114 => self.read_prg_mapper114(addr),
            PrgReadHandler::Mapper115 => self.read_prg_mapper115(addr),
            PrgReadHandler::Mapper123 => self.read_prg_mapper123(addr),
            PrgReadHandler::Mapper205 => self.read_prg_mapper205(addr),
            PrgReadHandler::Mmc1 => self.read_prg_mmc1(addr, rom_addr),
            PrgReadHandler::Mapper208 => self.read_prg_mapper208(addr),
            PrgReadHandler::Mapper15 => self.read_prg_mapper15(addr),
            PrgReadHandler::Mapper221 => self.read_prg_mapper221(addr),
            PrgReadHandler::Mapper225 => self.read_prg_mapper225(addr),
            PrgReadHandler::Mapper230 => self.read_prg_mapper230(addr),
            PrgReadHandler::Mapper227 => self.read_prg_mapper227(addr),
            PrgReadHandler::Mapper231 => self.read_prg_mapper231(addr),
            PrgReadHandler::Mapper236 => self.read_prg_mapper236(addr),
            PrgReadHandler::Mapper232 => self.read_prg_mapper232(addr),
            PrgReadHandler::Mapper233 => self.read_prg_mapper233(addr),
            PrgReadHandler::Mapper234 => self.read_prg_mapper234(addr),
            PrgReadHandler::Mapper235 => self.read_prg_mapper235(addr),
            PrgReadHandler::Mapper246 => self.read_prg_mapper246(addr),
            PrgReadHandler::Mapper200 => self.read_prg_mapper200(addr),
            PrgReadHandler::Mapper202 => self.read_prg_mapper202(addr),
            PrgReadHandler::Mapper212 => self.read_prg_mapper212(addr),
            PrgReadHandler::Mapper226 => self.read_prg_mapper226(addr),
            PrgReadHandler::Mapper228 => self.read_prg_mapper228(addr),
            PrgReadHandler::Mapper242 => self.read_prg_mapper242(addr),
            PrgReadHandler::Uxrom => self.read_prg_uxrom(addr, rom_addr),
            PrgReadHandler::Mapper50 => self.read_prg_mapper50(addr),
            PrgReadHandler::Mapper58 => self.read_prg_mapper58(addr),
            PrgReadHandler::Mapper65 => self.read_prg_mapper65(addr),
            PrgReadHandler::Sunsoft3 => self.read_prg_sunsoft3(addr),
            PrgReadHandler::Mapper229 => self.read_prg_mapper229(addr),
            PrgReadHandler::UxromInverted => self.read_prg_uxrom_inverted(addr, rom_addr),
            PrgReadHandler::FixedLastSwitchHigh => {
                self.read_prg_fixed_last_switch_high(addr, rom_addr)
            }
            PrgReadHandler::Mapper103 => self.read_prg_mapper103(addr),
            PrgReadHandler::Mapper191 => self.read_prg_mapper191(addr),
            PrgReadHandler::Mapper245 => self.read_prg_mapper245(addr),
            PrgReadHandler::Sunsoft4 => self.read_prg_sunsoft4(addr),
            PrgReadHandler::Vrc1 => self.read_prg_vrc1(addr),
            PrgReadHandler::TaitoX1005 => self.read_prg_taito_x1005(addr),
            PrgReadHandler::TaitoX1017 => self.read_prg_taito_x1017(addr),
            PrgReadHandler::Mmc2 => self.read_prg_mmc2(addr, rom_addr),
            PrgReadHandler::Bandai => self.read_prg_bandai(addr),
            PrgReadHandler::Fme7 => self.read_prg_fme7(addr),
            PrgReadHandler::Zero => 0,
        }
    }

    fn prg_read_handler(&self) -> PrgReadHandler {
        match self.mapper {
            210 => PrgReadHandler::Mapper210,
            21 => PrgReadHandler::Mapper21,
            22 => PrgReadHandler::Mapper22,
            23 => PrgReadHandler::Mapper23,
            _ if self.uses_vrc6() => PrgReadHandler::Vrc6,
            _ if self.uses_vrc7() => PrgReadHandler::Vrc7,
            25 => PrgReadHandler::Mapper25,
            18 => PrgReadHandler::Mapper18,
            _ if self.uses_namco163() => PrgReadHandler::Namco163,
            _ if self.uses_mmc5() => PrgReadHandler::Mmc5,
            64 => PrgReadHandler::Mapper64,
            0 | 3 | 13 | 87 | 101 | 184 | 185 => PrgReadHandler::Nrom,
            59 => PrgReadHandler::Mapper59,
            60 => PrgReadHandler::Mapper60,
            61 => PrgReadHandler::Mapper61,
            63 => PrgReadHandler::Mapper63,
            99 => PrgReadHandler::Mapper99,
            142 => PrgReadHandler::Mapper142,
            34 | 38 | 41 | 46 | 77 | 79 | 113 | 133 | 137 | 140 | 144 | 146 | 147 | 148 | 150
            | 189 | 201 | 240 | 241 | 243 | 7 | 11 | 66 | 107 => PrgReadHandler::Axrom,
            4 | 12 | 74 | 118 | 119 | 192 | 194 | 195 | 250 => PrgReadHandler::Mmc3,
            37 => PrgReadHandler::Mapper37,
            44 => PrgReadHandler::Mapper44,
            32 => PrgReadHandler::Mapper32,
            40 => PrgReadHandler::Mapper40,
            42 => PrgReadHandler::Mapper42,
            43 => PrgReadHandler::Mapper43,
            47 => PrgReadHandler::Mapper47,
            _ if self.uses_taito_tc0190() => PrgReadHandler::TaitoTc0190,
            _ if self.uses_namco108() => PrgReadHandler::Namco108,
            114 | 182 => PrgReadHandler::Mapper114,
            115 | 248 => PrgReadHandler::Mapper115,
            123 => PrgReadHandler::Mapper123,
            205 => PrgReadHandler::Mapper205,
            1 => PrgReadHandler::Mmc1,
            208 => PrgReadHandler::Mapper208,
            15 => PrgReadHandler::Mapper15,
            221 => PrgReadHandler::Mapper221,
            225 | 255 => PrgReadHandler::Mapper225,
            230 => PrgReadHandler::Mapper230,
            227 => PrgReadHandler::Mapper227,
            231 => PrgReadHandler::Mapper231,
            236 => PrgReadHandler::Mapper236,
            232 => PrgReadHandler::Mapper232,
            233 => PrgReadHandler::Mapper233,
            234 => PrgReadHandler::Mapper234,
            235 => PrgReadHandler::Mapper235,
            246 => PrgReadHandler::Mapper246,
            200 | 203 => PrgReadHandler::Mapper200,
            202 => PrgReadHandler::Mapper202,
            212 => PrgReadHandler::Mapper212,
            226 => PrgReadHandler::Mapper226,
            228 => PrgReadHandler::Mapper228,
            242 => PrgReadHandler::Mapper242,
            2 | 57 | 70 | 71 | 72 | 73 | 78 | 81 | 86 | 89 | 93 | 94 | 152 => PrgReadHandler::Uxrom,
            50 => PrgReadHandler::Mapper50,
            58 | 213 => PrgReadHandler::Mapper58,
            65 => PrgReadHandler::Mapper65,
            67 => PrgReadHandler::Sunsoft3,
            229 => PrgReadHandler::Mapper229,
            92 | 180 => PrgReadHandler::UxromInverted,
            97 => PrgReadHandler::FixedLastSwitchHigh,
            103 => PrgReadHandler::Mapper103,
            191 => PrgReadHandler::Mapper191,
            245 => PrgReadHandler::Mapper245,
            68 => PrgReadHandler::Sunsoft4,
            _ if self.uses_vrc1() => PrgReadHandler::Vrc1,
            _ if self.uses_taito_x1005() => PrgReadHandler::TaitoX1005,
            _ if self.uses_taito_x1017() => PrgReadHandler::TaitoX1017,
            _ if self.uses_mmc2_latches() => PrgReadHandler::Mmc2,
            _ if self.uses_bandai_fcg() => PrgReadHandler::Bandai,
            _ if self.uses_fme7() => PrgReadHandler::Fme7,
            _ => PrgReadHandler::Zero,
        }
    }
}
