use super::*;

impl Cpu {
    pub(super) fn execute_instruction(&mut self, opcode: u8, bus: &mut dyn CpuBus) -> u8 {
        match opcode {
            0x00 => self.brk(bus),
            0x01 => self.ora_indexed_indirect(bus),
            0x05 => self.ora_zero_page(bus),
            0x06 => self.asl_zero_page(bus),
            0x08 => self.php(bus),
            0x09 => self.ora_immediate(bus),
            0x0A => self.asl_accumulator(),
            0x0D => self.ora_absolute(bus),
            0x0E => self.asl_absolute(bus),

            0x10 => self.bpl(bus),
            0x11 => self.ora_indirect_indexed(bus),
            0x15 => self.ora_zero_page_x(bus),
            0x16 => self.asl_zero_page_x(bus),
            0x18 => self.clc(),
            0x19 => self.ora_absolute_y(bus),
            0x1D => self.ora_absolute_x(bus),
            0x1E => self.asl_absolute_x(bus),

            0x20 => self.jsr(bus),
            0x21 => self.and_indexed_indirect(bus),
            0x24 => self.bit_zero_page(bus),
            0x25 => self.and_zero_page(bus),
            0x26 => self.rol_zero_page(bus),
            0x28 => self.plp(bus),
            0x29 => self.and_immediate(bus),
            0x2A => self.rol_accumulator(),
            0x2C => self.bit_absolute(bus),
            0x2D => self.and_absolute(bus),
            0x2E => self.rol_absolute(bus),

            0x30 => self.bmi(bus),
            0x31 => self.and_indirect_indexed(bus),
            0x35 => self.and_zero_page_x(bus),
            0x36 => self.rol_zero_page_x(bus),
            0x38 => self.sec(),
            0x39 => self.and_absolute_y(bus),
            0x3D => self.and_absolute_x(bus),
            0x3E => self.rol_absolute_x(bus),

            0x40 => self.rti(bus),
            0x41 => self.eor_indexed_indirect(bus),
            0x45 => self.eor_zero_page(bus),
            0x46 => self.lsr_zero_page(bus),
            0x47 => {
                // SRE zeropage - Shift Right and Exclusive OR
                let addr = self.read_byte(bus) as u16;
                let value = bus.read(addr);
                let shifted = value >> 1;
                bus.write(addr, shifted);
                self.status.set(StatusFlags::CARRY, value & 0x01 != 0);
                self.a ^= shifted;
                self.set_zero_negative_flags(self.a);
                5
            }
            0x48 => self.pha(bus),
            0x49 => self.eor_immediate(bus),
            0x4A => self.lsr_accumulator(),
            0x4C => self.jmp_absolute(bus),
            0x4D => self.eor_absolute(bus),
            0x4E => self.lsr_absolute(bus),

            0x50 => self.bvc(bus),
            0x51 => self.eor_indirect_indexed(bus),
            0x55 => self.eor_zero_page_x(bus),
            0x56 => self.lsr_zero_page_x(bus),
            0x58 => self.cli(),
            0x59 => self.eor_absolute_y(bus),
            0x5D => self.eor_absolute_x(bus),
            0x5E => self.lsr_absolute_x(bus),

            0x60 => self.rts(bus),
            0x61 => self.adc_indexed_indirect(bus),
            0x65 => self.adc_zero_page(bus),
            0x66 => self.ror_zero_page(bus),
            0x68 => self.pla(bus),
            0x69 => self.adc_immediate(bus),
            0x6A => self.ror_accumulator(),
            0x6C => self.jmp_indirect(bus),
            0x6D => self.adc_absolute(bus),
            0x6E => self.ror_absolute(bus),

            0x70 => self.bvs(bus),
            0x71 => self.adc_indirect_indexed(bus),
            0x75 => self.adc_zero_page_x(bus),
            0x76 => self.ror_zero_page_x(bus),
            0x78 => self.sei(),
            0x79 => self.adc_absolute_y(bus),
            0x7D => self.adc_absolute_x(bus),
            0x7E => self.ror_absolute_x(bus),

            0x81 => self.sta_indexed_indirect(bus),
            0x83 => self.sax_indexed_indirect(bus),
            0x84 => self.sty_zero_page(bus),
            0x85 => self.sta_zero_page(bus),
            0x86 => self.stx_zero_page(bus),
            0x88 => self.dey(),
            0x8A => self.txa(),
            0x8C => self.sty_absolute(bus),
            0x8D => self.sta_absolute(bus),
            0x8E => self.stx_absolute(bus),

            0x90 => self.bcc(bus),
            0x91 => self.sta_indirect_indexed(bus),
            0x94 => self.sty_zero_page_x(bus),
            0x95 => self.sta_zero_page_x(bus),
            0x96 => self.stx_zero_page_y(bus),
            0x98 => self.tya(),
            0x99 => self.sta_absolute_y(bus),
            0x9A => self.txs(),
            0x9D => self.sta_absolute_x(bus),

            0xA0 => self.ldy_immediate(bus),
            0xA1 => self.lda_indexed_indirect(bus),
            0xA2 => self.ldx_immediate(bus),
            0xA4 => self.ldy_zero_page(bus),
            0xA5 => self.lda_zero_page(bus),
            0xA6 => self.ldx_zero_page(bus),
            0xA8 => self.tay(),
            0xA9 => self.lda_immediate(bus),
            0xAA => self.tax(),
            0xAC => self.ldy_absolute(bus),
            0xAD => self.lda_absolute(bus),
            0xAE => self.ldx_absolute(bus),

            0xB0 => self.bcs(bus),
            0xB1 => self.lda_indirect_indexed(bus),
            0xB4 => self.ldy_zero_page_x(bus),
            0xB5 => self.lda_zero_page_x(bus),
            0xB6 => self.ldx_zero_page_y(bus),
            0xB8 => self.clv(),
            0xB9 => self.lda_absolute_y(bus),
            0xBA => self.tsx(),
            0xBC => self.ldy_absolute_x(bus),
            0xBD => self.lda_absolute_x(bus),
            0xBE => self.ldx_absolute_y(bus),

            0xC0 => self.cpy_immediate(bus),
            0xC1 => self.cmp_indexed_indirect(bus),
            0xC4 => self.cpy_zero_page(bus),
            0xC5 => self.cmp_zero_page(bus),
            0xC6 => self.dec_zero_page(bus),
            0xC8 => self.iny(),
            0xC9 => self.cmp_immediate(bus),
            0xCA => self.dex(),
            0xCC => self.cpy_absolute(bus),
            0xCD => self.cmp_absolute(bus),
            0xCE => self.dec_absolute(bus),

            0xD0 => self.bne(bus),
            0xD1 => self.cmp_indirect_indexed(bus),
            0xD5 => self.cmp_zero_page_x(bus),
            0xD6 => self.dec_zero_page_x(bus),
            0xD8 => self.cld(),
            0xD9 => self.cmp_absolute_y(bus),
            0xDD => self.cmp_absolute_x(bus),
            0xDE => self.dec_absolute_x(bus),

            0xE0 => self.cpx_immediate(bus),
            0xE1 => self.sbc_indexed_indirect(bus),
            0xE4 => self.cpx_zero_page(bus),
            0xE5 => self.sbc_zero_page(bus),
            0xE6 => self.inc_zero_page(bus),
            0xE8 => self.inx(),
            0xE9 => self.sbc_immediate(bus),
            0xEA => self.nop(),
            0xEC => self.cpx_absolute(bus),
            0xED => self.sbc_absolute(bus),
            0xEE => self.inc_absolute(bus),

            0xF0 => self.beq(bus),
            0xF1 => self.sbc_indirect_indexed(bus),
            0xF5 => self.sbc_zero_page_x(bus),
            0xF6 => self.inc_zero_page_x(bus),
            0xF8 => self.sed(),
            0xF9 => self.sbc_absolute_y(bus),
            0xFD => self.sbc_absolute_x(bus),
            0xFE => self.inc_absolute_x(bus),

            _ => self.execute_unofficial_instruction(opcode, bus),
        }
    }
}
