use crate::cartridge::Cartridge;

#[derive(Clone, Copy)]
enum ChrWriteHandler {
    Mapper210,
    Mapper21,
    Mapper22,
    Mapper23,
    Vrc6,
    Mapper25,
    Mapper18,
    Namco163,
    Mmc5,
    Nrom,
    Mmc1,
    Uxrom,
    Mapper32,
    Mapper65,
    Mapper221,
    Mapper227,
    Mapper231,
    Mapper236,
    Vrc1,
    Cprom,
    Nina001,
    Split4k,
    TaitoTc0190,
    Cnrom,
    Mapper63,
    Mapper64,
    Mapper137,
    Mapper77,
    Sunsoft3,
    Mapper185,
    Mmc3,
    Mapper242,
    Mapper93,
    Mapper12,
    Mapper37,
    Mapper44,
    Mapper47,
    Mapper114,
    Mapper115,
    Mapper205,
    Mapper74,
    Mapper119,
    Mapper191,
    Mapper192,
    Mapper194,
    Mapper195,
    Mapper245,
    Sunsoft4,
    TaitoX1005,
    TaitoX1017,
    Namco108,
    Mmc2,
    Bandai,
    Fme7,
    None,
    RawChrRom,
}

impl Cartridge {
    pub fn write_chr(&mut self, addr: u16, data: u8) {
        match self.chr_write_handler() {
            ChrWriteHandler::Mapper210 => self.write_chr_mapper210(addr, data),
            ChrWriteHandler::Mapper21 => self.write_chr_mapper21(addr, data),
            ChrWriteHandler::Mapper22 => self.write_chr_mapper22(addr, data),
            ChrWriteHandler::Mapper23 => self.write_chr_mapper23(addr, data),
            ChrWriteHandler::Vrc6 => self.write_chr_vrc6(addr, data),
            ChrWriteHandler::Mapper25 => self.write_chr_mapper25(addr, data),
            ChrWriteHandler::Mapper18 => self.write_chr_mapper18(addr, data),
            ChrWriteHandler::Namco163 => self.write_chr_namco163(addr, data),
            ChrWriteHandler::Mmc5 => self.write_chr_mmc5(addr, data),
            ChrWriteHandler::Nrom => self.write_chr_nrom(addr, data),
            ChrWriteHandler::Mmc1 => self.write_chr_mmc1(addr, data),
            ChrWriteHandler::Uxrom => self.write_chr_uxrom(addr, data),
            ChrWriteHandler::Mapper32 => self.write_chr_mapper32(addr, data),
            ChrWriteHandler::Mapper65 => self.write_chr_mapper65(addr, data),
            ChrWriteHandler::Mapper221 => self.write_chr_mapper221(addr, data),
            ChrWriteHandler::Mapper227 => self.write_chr_mapper227(addr, data),
            ChrWriteHandler::Mapper231 => self.write_chr_mapper231(addr, data),
            ChrWriteHandler::Mapper236 => self.write_chr_mapper236(addr, data),
            ChrWriteHandler::Vrc1 => self.write_chr_vrc1(addr, data),
            ChrWriteHandler::Cprom => self.write_chr_cprom(addr, data),
            ChrWriteHandler::Nina001 => self.write_chr_nina001(addr, data),
            ChrWriteHandler::Split4k => self.write_chr_split_4k(addr, data),
            ChrWriteHandler::TaitoTc0190 => self.write_chr_taito_tc0190(addr, data),
            ChrWriteHandler::Cnrom => self.write_chr_cnrom(addr, data),
            ChrWriteHandler::Mapper63 => self.write_chr_mapper63(addr, data),
            ChrWriteHandler::Mapper64 => self.write_chr_mapper64(addr, data),
            ChrWriteHandler::Mapper137 => self.write_chr_mapper137(addr, data),
            ChrWriteHandler::Mapper77 => self.write_chr_mapper77(addr, data),
            ChrWriteHandler::Sunsoft3 => self.write_chr_sunsoft3(addr, data),
            ChrWriteHandler::Mapper185 => self.write_chr_mapper185(addr, data),
            ChrWriteHandler::Mmc3 => self.write_chr_mmc3(addr, data),
            ChrWriteHandler::Mapper242 => self.write_chr_mapper242(addr, data),
            ChrWriteHandler::Mapper93 => self.write_chr_mapper93(addr, data),
            ChrWriteHandler::Mapper12 => self.write_chr_mapper12(addr, data),
            ChrWriteHandler::Mapper37 => self.write_chr_mapper37(addr, data),
            ChrWriteHandler::Mapper44 => self.write_chr_mapper44(addr, data),
            ChrWriteHandler::Mapper47 => self.write_chr_mapper47(addr, data),
            ChrWriteHandler::Mapper114 => self.write_chr_mapper114(addr, data),
            ChrWriteHandler::Mapper115 => self.write_chr_mapper115(addr, data),
            ChrWriteHandler::Mapper205 => self.write_chr_mapper205(addr, data),
            ChrWriteHandler::Mapper74 => self.write_chr_mapper74(addr, data),
            ChrWriteHandler::Mapper119 => self.write_chr_mapper119(addr, data),
            ChrWriteHandler::Mapper191 => self.write_chr_mapper191(addr, data),
            ChrWriteHandler::Mapper192 => self.write_chr_mapper192(addr, data),
            ChrWriteHandler::Mapper194 => self.write_chr_mapper194(addr, data),
            ChrWriteHandler::Mapper195 => self.write_chr_mapper195(addr, data),
            ChrWriteHandler::Mapper245 => self.write_chr_mapper245(addr, data),
            ChrWriteHandler::Sunsoft4 => self.write_chr_sunsoft4(addr, data),
            ChrWriteHandler::TaitoX1005 => self.write_chr_taito_x1005(addr, data),
            ChrWriteHandler::TaitoX1017 => self.write_chr_taito_x1017(addr, data),
            ChrWriteHandler::Namco108 => self.write_chr_namco108(addr, data),
            ChrWriteHandler::Mmc2 => self.write_chr_mmc2(addr, data),
            ChrWriteHandler::Bandai => self.write_chr_bandai(addr, data),
            ChrWriteHandler::Fme7 => self.write_chr_fme7(addr, data),
            ChrWriteHandler::None => {}
            ChrWriteHandler::RawChrRom => {
                self.chr_rom[(addr & 0x1FFF) as usize] = data;
            }
        }
    }

    fn chr_write_handler(&self) -> ChrWriteHandler {
        match self.mapper {
            210 => ChrWriteHandler::Mapper210,
            21 => ChrWriteHandler::Mapper21,
            22 => ChrWriteHandler::Mapper22,
            23 => ChrWriteHandler::Mapper23,
            24 | 26 => ChrWriteHandler::Vrc6,
            25 => ChrWriteHandler::Mapper25,
            18 => ChrWriteHandler::Mapper18,
            19 => ChrWriteHandler::Namco163,
            5 => ChrWriteHandler::Mmc5,
            34 if self.mappers.simple.mapper34_nina001 => ChrWriteHandler::Nina001,
            0 | 34 | 43 | 97 | 103 | 142 | 226 | 241 => ChrWriteHandler::Nrom,
            1 => ChrWriteHandler::Mmc1,
            2 | 7 | 15 | 40 | 42 | 50 | 71 | 73 | 94 | 180 | 230 | 232 | 235 => {
                ChrWriteHandler::Uxrom
            }
            32 => ChrWriteHandler::Mapper32,
            65 => ChrWriteHandler::Mapper65,
            221 => ChrWriteHandler::Mapper221,
            227 => ChrWriteHandler::Mapper227,
            231 => ChrWriteHandler::Mapper231,
            236 => ChrWriteHandler::Mapper236,
            75 | 151 => ChrWriteHandler::Vrc1,
            13 => ChrWriteHandler::Cprom,
            184 => ChrWriteHandler::Split4k,
            33 | 48 => ChrWriteHandler::TaitoTc0190,
            3 | 11 | 38 | 41 | 46 | 57 | 58 | 59 | 60 | 61 | 66 | 70 | 72 | 78 | 79 | 81 | 86
            | 87 | 89 | 92 | 101 | 107 | 113 | 133 | 140 | 144 | 145 | 146 | 147 | 148 | 150
            | 152 | 200 | 201 | 202 | 203 | 212 | 213 | 225 | 228 | 229 | 233 | 234 | 240 | 243
            | 255 => ChrWriteHandler::Cnrom,
            63 => ChrWriteHandler::Mapper63,
            64 => ChrWriteHandler::Mapper64,
            99 | 246 => ChrWriteHandler::None,
            137 => ChrWriteHandler::Mapper137,
            77 => ChrWriteHandler::Mapper77,
            67 => ChrWriteHandler::Sunsoft3,
            185 => ChrWriteHandler::Mapper185,
            4 | 118 | 123 | 189 | 208 | 250 => ChrWriteHandler::Mmc3,
            242 => ChrWriteHandler::Mapper242,
            93 => ChrWriteHandler::Mapper93,
            12 => ChrWriteHandler::Mapper12,
            37 => ChrWriteHandler::Mapper37,
            44 => ChrWriteHandler::Mapper44,
            47 => ChrWriteHandler::Mapper47,
            114 | 182 => ChrWriteHandler::Mapper114,
            115 | 248 => ChrWriteHandler::Mapper115,
            205 => ChrWriteHandler::Mapper205,
            74 => ChrWriteHandler::Mapper74,
            119 => ChrWriteHandler::Mapper119,
            191 => ChrWriteHandler::Mapper191,
            192 => ChrWriteHandler::Mapper192,
            194 => ChrWriteHandler::Mapper194,
            195 => ChrWriteHandler::Mapper195,
            245 => ChrWriteHandler::Mapper245,
            68 => ChrWriteHandler::Sunsoft4,
            80 | 207 => ChrWriteHandler::TaitoX1005,
            82 => ChrWriteHandler::TaitoX1017,
            76 | 88 | 95 | 112 | 154 | 206 => ChrWriteHandler::Namco108,
            9 | 10 => ChrWriteHandler::Mmc2,
            16 | 153 | 159 => ChrWriteHandler::Bandai,
            69 => ChrWriteHandler::Fme7,
            _ => ChrWriteHandler::RawChrRom,
        }
    }
}
