[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.5"

[alias]
build-native = "build --profile release-native"
run-native = "run --profile release-native"
build-apple = "build --profile release-native --target aarch64-apple-darwin"
run-apple = "run --profile release-native --target aarch64-apple-darwin"

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "target-cpu=native",
]
