use super::*;

#[derive(Clone, Copy)]
enum PrgRamReadHandler {
    Mapper210,
    Mapper21,
    Mapper22,
    Mapper23,
    Vrc6,
    Vrc7,
    Mapper25,
    Mapper18,
    Namco163,
    Mmc5,
    Mmc1,
    Mapper15,
    Mapper40,
    Mapper42,
    Mapper43,
    Mapper50,
    Vrc3,
    Mapper99,
    Mapper142,
    TaitoX1005,
    TaitoX1017,
    Linear,
    Constant80,
    Mapper246,
    Mmc3,
    Mapper115,
    Sunsoft4,
    Mmc2,
    Bandai,
    Mapper103,
    Fme7,
    None,
}

impl Cartridge {
    pub fn read_prg_ram(&self, addr: u16) -> u8 {
        match self.prg_ram_read_handler() {
            PrgRamReadHandler::Mapper210 => self.read_prg_ram_mapper210(addr),
            PrgRamReadHandler::Mapper21 => self.read_prg_ram_mapper21(addr),
            PrgRamReadHandler::Mapper22 => self.read_prg_ram_mapper22(addr),
            PrgRamReadHandler::Mapper23 => self.read_prg_ram_mapper23(addr),
            PrgRamReadHandler::Vrc6 => self.read_prg_ram_vrc6(addr),
            PrgRamReadHandler::Vrc7 => self.read_prg_ram_vrc7(addr),
            PrgRamReadHandler::Mapper25 => self.read_prg_ram_mapper25(addr),
            PrgRamReadHandler::Mapper18 => self.read_prg_ram_mapper18(addr),
            PrgRamReadHandler::Namco163 => self.read_prg_ram_namco163(addr),
            PrgRamReadHandler::Mmc5 => self.read_prg_ram_mmc5(addr),
            PrgRamReadHandler::Mmc1 => self.read_prg_ram_mmc1(addr),
            PrgRamReadHandler::Mapper15 => self.read_prg_ram_mapper15(addr),
            PrgRamReadHandler::Mapper40 => self.read_prg_ram_mapper40(addr),
            PrgRamReadHandler::Mapper42 => self.read_prg_ram_mapper42(addr),
            PrgRamReadHandler::Mapper43 => self.read_prg_ram_mapper43(addr),
            PrgRamReadHandler::Mapper50 => self.read_prg_ram_mapper50(addr),
            PrgRamReadHandler::Vrc3 => self.read_prg_ram_vrc3(addr),
            PrgRamReadHandler::Mapper99 => self.read_prg_ram_mapper99(addr),
            PrgRamReadHandler::Mapper142 => self.read_prg_ram_mapper142(addr),
            PrgRamReadHandler::TaitoX1005 => self.read_prg_ram_taito_x1005(addr),
            PrgRamReadHandler::TaitoX1017 => self.read_prg_ram_taito_x1017(addr),
            PrgRamReadHandler::Linear => self.read_linear_prg_ram(addr),
            PrgRamReadHandler::Constant80 => 0x80,
            PrgRamReadHandler::Mapper246 => self.read_prg_ram_mapper246(addr),
            PrgRamReadHandler::Mmc3 => self.read_prg_ram_mmc3(addr),
            PrgRamReadHandler::Mapper115 => self.read_prg_ram_mapper115(addr),
            PrgRamReadHandler::Sunsoft4 => self.read_prg_ram_sunsoft4(addr),
            PrgRamReadHandler::Mmc2 => self.read_prg_ram_mmc2(addr),
            PrgRamReadHandler::Bandai => self.read_prg_ram_bandai(addr),
            PrgRamReadHandler::Mapper103 => self.read_prg_ram_mapper103(addr),
            PrgRamReadHandler::Fme7 => self.read_prg_ram_fme7(addr),
            PrgRamReadHandler::None => 0,
        }
    }

    fn prg_ram_read_handler(&self) -> PrgRamReadHandler {
        match self.mapper {
            210 => PrgRamReadHandler::Mapper210,
            21 => PrgRamReadHandler::Mapper21,
            22 => PrgRamReadHandler::Mapper22,
            23 => PrgRamReadHandler::Mapper23,
            24 | 26 => PrgRamReadHandler::Vrc6,
            85 => PrgRamReadHandler::Vrc7,
            25 => PrgRamReadHandler::Mapper25,
            18 => PrgRamReadHandler::Mapper18,
            19 => PrgRamReadHandler::Namco163,
            5 => PrgRamReadHandler::Mmc5,
            1 => PrgRamReadHandler::Mmc1,
            15 => PrgRamReadHandler::Mapper15,
            40 => PrgRamReadHandler::Mapper40,
            42 => PrgRamReadHandler::Mapper42,
            43 => PrgRamReadHandler::Mapper43,
            50 => PrgRamReadHandler::Mapper50,
            73 => PrgRamReadHandler::Vrc3,
            99 => PrgRamReadHandler::Mapper99,
            142 => PrgRamReadHandler::Mapper142,
            80 | 207 => PrgRamReadHandler::TaitoX1005,
            82 => PrgRamReadHandler::TaitoX1017,
            34 if self.mappers.simple.mapper34_nina001 => PrgRamReadHandler::Linear,
            227 | 240 | 241 => PrgRamReadHandler::Linear,
            212 => PrgRamReadHandler::Constant80,
            246 => PrgRamReadHandler::Mapper246,
            4 | 74 | 118 | 119 | 192 | 194 | 245 | 250 => PrgRamReadHandler::Mmc3,
            115 | 248 => PrgRamReadHandler::Mapper115,
            68 => PrgRamReadHandler::Sunsoft4,
            9 | 10 => PrgRamReadHandler::Mmc2,
            16 | 153 | 159 => PrgRamReadHandler::Bandai,
            103 => PrgRamReadHandler::Mapper103,
            69 => PrgRamReadHandler::Fme7,
            _ => PrgRamReadHandler::None,
        }
    }
}
