use super::*;

#[derive(Clone, Copy)]
enum PrgRamWriteHandler {
    Mapper210,
    Mapper21,
    Mapper22,
    Mapper23,
    Vrc6,
    Mapper25,
    Mapper18,
    Namco163,
    Mmc5,
    Mapper46Outer,
    Mapper41,
    Mapper38,
    Mapper87,
    Mapper86,
    Mapper101,
    Mapper15,
    Vrc3,
    Mapper99,
    Mapper208,
    Mapper37,
    Mapper47,
    Mapper114,
    Mapper115,
    Mapper205,
    TaitoX1005,
    TaitoX1017,
    Mapper140,
    Mapper189,
    Mmc1,
    Mapper103,
    Nina001,
    Mapper184,
    Linear,
    Mmc3,
    Sunsoft4,
    Mapper246,
    Mmc2,
    Bandai,
    Fme7,
    None,
}

impl Cartridge {
    pub fn write_prg_ram(&mut self, addr: u16, data: u8) {
        match self.prg_ram_write_handler() {
            PrgRamWriteHandler::Mapper210 => self.write_prg_ram_mapper210(addr, data),
            PrgRamWriteHandler::Mapper21 => self.write_prg_ram_mapper21(addr, data),
            PrgRamWriteHandler::Mapper22 => self.write_prg_ram_mapper22(addr, data),
            PrgRamWriteHandler::Mapper23 => self.write_prg_ram_mapper23(addr, data),
            PrgRamWriteHandler::Vrc6 => self.write_prg_ram_vrc6(addr, data),
            PrgRamWriteHandler::Mapper25 => self.write_prg_ram_mapper25(addr, data),
            PrgRamWriteHandler::Mapper18 => self.write_prg_ram_mapper18(addr, data),
            PrgRamWriteHandler::Namco163 => self.write_prg_ram_namco163(addr, data),
            PrgRamWriteHandler::Mmc5 => self.write_prg_ram_mmc5(addr, data),
            PrgRamWriteHandler::Mapper46Outer => self.write_prg_mapper46_outer(addr, data),
            PrgRamWriteHandler::Mapper41 => self.write_prg_ram_mapper41(addr),
            PrgRamWriteHandler::Mapper38 => self.write_prg_mapper38(addr, data),
            PrgRamWriteHandler::Mapper87 => self.write_prg_mapper87(addr, data),
            PrgRamWriteHandler::Mapper86 => self.write_prg_mapper86(addr, data),
            PrgRamWriteHandler::Mapper101 => self.write_prg_mapper101(addr, data),
            PrgRamWriteHandler::Mapper15 => self.write_prg_ram_mapper15(addr, data),
            PrgRamWriteHandler::Vrc3 => self.write_prg_ram_vrc3(addr, data),
            PrgRamWriteHandler::Mapper99 => self.write_prg_ram_mapper99(addr, data),
            PrgRamWriteHandler::Mapper208 => self.write_prg_ram_mapper208(addr, data),
            PrgRamWriteHandler::Mapper37 => self.write_prg_ram_mapper37(addr, data),
            PrgRamWriteHandler::Mapper47 => self.write_prg_ram_mapper47(addr, data),
            PrgRamWriteHandler::Mapper114 => self.write_prg_ram_mapper114(addr, data),
            PrgRamWriteHandler::Mapper115 => self.write_prg_ram_mapper115(addr, data),
            PrgRamWriteHandler::Mapper205 => self.write_prg_ram_mapper205(addr, data),
            PrgRamWriteHandler::TaitoX1005 => self.write_prg_ram_taito_x1005(addr, data),
            PrgRamWriteHandler::TaitoX1017 => self.write_prg_ram_taito_x1017(addr, data),
            PrgRamWriteHandler::Mapper140 => self.write_prg_mapper140(addr, data),
            PrgRamWriteHandler::Mapper189 => self.write_prg_ram_mapper189(data),
            PrgRamWriteHandler::Mmc1 => self.write_prg_ram_mmc1(addr, data),
            PrgRamWriteHandler::Mapper103 => self.write_prg_ram_mapper103(addr, data),
            PrgRamWriteHandler::Nina001 => self.write_prg_ram_nina001(addr, data),
            PrgRamWriteHandler::Mapper184 => self.write_prg_mapper184(addr, data),
            PrgRamWriteHandler::Linear => self.write_linear_prg_ram(addr, data),
            PrgRamWriteHandler::Mmc3 => self.write_prg_ram_mmc3(addr, data),
            PrgRamWriteHandler::Sunsoft4 => self.write_prg_ram_sunsoft4(addr, data),
            PrgRamWriteHandler::Mapper246 => self.write_prg_ram_mapper246(addr, data),
            PrgRamWriteHandler::Mmc2 => self.write_prg_ram_mmc2(addr, data),
            PrgRamWriteHandler::Bandai => self.write_prg_ram_bandai(addr, data),
            PrgRamWriteHandler::Fme7 => self.write_prg_ram_fme7(addr, data),
            PrgRamWriteHandler::None => {}
        }
    }

    fn prg_ram_write_handler(&self) -> PrgRamWriteHandler {
        match self.mapper {
            210 => PrgRamWriteHandler::Mapper210,
            21 => PrgRamWriteHandler::Mapper21,
            22 => PrgRamWriteHandler::Mapper22,
            23 => PrgRamWriteHandler::Mapper23,
            24 | 26 => PrgRamWriteHandler::Vrc6,
            25 => PrgRamWriteHandler::Mapper25,
            18 => PrgRamWriteHandler::Mapper18,
            19 => PrgRamWriteHandler::Namco163,
            5 => PrgRamWriteHandler::Mmc5,
            46 => PrgRamWriteHandler::Mapper46Outer,
            41 => PrgRamWriteHandler::Mapper41,
            38 => PrgRamWriteHandler::Mapper38,
            87 => PrgRamWriteHandler::Mapper87,
            86 => PrgRamWriteHandler::Mapper86,
            101 => PrgRamWriteHandler::Mapper101,
            15 => PrgRamWriteHandler::Mapper15,
            73 => PrgRamWriteHandler::Vrc3,
            99 => PrgRamWriteHandler::Mapper99,
            208 => PrgRamWriteHandler::Mapper208,
            37 => PrgRamWriteHandler::Mapper37,
            47 => PrgRamWriteHandler::Mapper47,
            114 | 182 => PrgRamWriteHandler::Mapper114,
            115 | 248 => PrgRamWriteHandler::Mapper115,
            205 => PrgRamWriteHandler::Mapper205,
            80 | 207 => PrgRamWriteHandler::TaitoX1005,
            82 => PrgRamWriteHandler::TaitoX1017,
            140 => PrgRamWriteHandler::Mapper140,
            189 => PrgRamWriteHandler::Mapper189,
            1 => PrgRamWriteHandler::Mmc1,
            103 => PrgRamWriteHandler::Mapper103,
            34 if self.mappers.simple.mapper34_nina001 => PrgRamWriteHandler::Nina001,
            184 => PrgRamWriteHandler::Mapper184,
            227 | 240 | 241 => PrgRamWriteHandler::Linear,
            4 | 74 | 118 | 119 | 192 | 194 | 245 | 250 => PrgRamWriteHandler::Mmc3,
            68 => PrgRamWriteHandler::Sunsoft4,
            246 => PrgRamWriteHandler::Mapper246,
            9 | 10 => PrgRamWriteHandler::Mmc2,
            16 | 153 | 159 => PrgRamWriteHandler::Bandai,
            69 => PrgRamWriteHandler::Fme7,
            _ => PrgRamWriteHandler::None,
        }
    }
}
