use crate::cartridge::Cartridge;

#[derive(Clone, Copy)]
enum PrgWriteHandler {
    None,
    Mapper210,
    Mapper21,
    Mapper22,
    Mapper23,
    Vrc6,
    Vrc7,
    Mapper25,
    Mapper18,
    Namco163,
    Mmc5,
    Mapper64,
    Mapper32,
    Mapper40,
    Mapper42,
    Mapper43,
    Mmc1,
    Mapper50,
    Vrc3,
    Mapper208,
    Mapper15,
    TaitoTc0190,
    Mapper221,
    Uxrom,
    Mapper225,
    Mapper230,
    Mapper227,
    Mapper231,
    Mapper236,
    Mapper41,
    Mapper232,
    Mapper233,
    Mapper234,
    Mapper235,
    Cnrom,
    Cprom,
    Bnrom,
    Mapper46Inner,
    Mapper191,
    Mmc3,
    Mapper12,
    Mapper44,
    Mapper48,
    Mapper114,
    Mapper123,
    Mapper250,
    Mapper57,
    Mapper59,
    Mapper61,
    Mapper63,
    Mapper137,
    Mapper142,
    Mapper150,
    Mapper58,
    Mapper65,
    Sunsoft3,
    Mapper72_92,
    Sunsoft4,
    Vrc1,
    Namco108,
    Axrom,
    Mapper77,
    Mapper200,
    Mapper201,
    Mapper202,
    Mapper203,
    Mapper212,
    Mapper226,
    Mapper228,
    Mapper229,
    Mapper242,
    Mapper243,
    Mapper241,
    Mapper79_146,
    Mapper133,
    Mapper113,
    Mapper144,
    Mapper145,
    ColorDreams,
    Mapper189,
    Mapper89,
    Mapper93,
    Mapper70,
    Camerica,
    Mapper81,
    Mapper97,
    Mapper103,
    Mapper78,
    Mapper86,
    Mapper94,
    Mapper107,
    Mapper147,
    Mapper148,
    Mapper152,
    UxromInverted,
    Mapper240,
    Mmc2,
    Bandai,
    Gxrom,
    Fme7,
    Mapper87,
}

impl Cartridge {
    pub fn write_prg(&mut self, addr: u16, data: u8) {
        match self.prg_write_handler() {
            PrgWriteHandler::None => {}
            PrgWriteHandler::Mapper210 => self.write_prg_mapper210(addr, data),
            PrgWriteHandler::Mapper21 => self.write_prg_mapper21(addr, data),
            PrgWriteHandler::Mapper22 => self.write_prg_mapper22(addr, data),
            PrgWriteHandler::Mapper23 => self.write_prg_mapper23(addr, data),
            PrgWriteHandler::Vrc6 => self.write_prg_vrc6(addr, data),
            PrgWriteHandler::Vrc7 => self.write_prg_vrc7(addr, data),
            PrgWriteHandler::Mapper25 => self.write_prg_mapper25(addr, data),
            PrgWriteHandler::Mapper18 => self.write_prg_mapper18(addr, data),
            PrgWriteHandler::Namco163 => self.write_prg_namco163(addr, data),
            PrgWriteHandler::Mmc5 => self.write_prg_mmc5(addr, data),
            PrgWriteHandler::Mapper64 => self.write_prg_mapper64(addr, data),
            PrgWriteHandler::Mapper32 => self.write_prg_mapper32(addr, data),
            PrgWriteHandler::Mapper40 => self.write_prg_mapper40(addr, data),
            PrgWriteHandler::Mapper42 => self.write_prg_mapper42(addr, data),
            PrgWriteHandler::Mapper43 => self.write_prg_mapper43(addr, data),
            PrgWriteHandler::Mmc1 => self.write_prg_mmc1(addr, data),
            PrgWriteHandler::Mapper50 => self.write_prg_mapper50(addr, data),
            PrgWriteHandler::Vrc3 => self.write_prg_vrc3(addr, data),
            PrgWriteHandler::Mapper208 => self.write_prg_mapper208(addr, data),
            PrgWriteHandler::Mapper15 => self.write_prg_mapper15(addr, data),
            PrgWriteHandler::TaitoTc0190 => self.write_prg_taito_tc0190(addr, data),
            PrgWriteHandler::Mapper221 => self.write_prg_mapper221(addr),
            PrgWriteHandler::Uxrom => self.write_prg_uxrom(addr, data),
            PrgWriteHandler::Mapper225 => self.write_prg_mapper225(addr, data),
            PrgWriteHandler::Mapper230 => self.write_prg_mapper230(addr, data),
            PrgWriteHandler::Mapper227 => self.write_prg_mapper227(addr),
            PrgWriteHandler::Mapper231 => self.write_prg_mapper231(addr),
            PrgWriteHandler::Mapper236 => self.write_prg_mapper236(addr, data),
            PrgWriteHandler::Mapper41 => self.write_prg_mapper41(addr, data),
            PrgWriteHandler::Mapper232 => self.write_prg_mapper232(addr, data),
            PrgWriteHandler::Mapper233 => self.write_prg_mapper233(addr, data),
            PrgWriteHandler::Mapper234 => self.write_prg_mapper234(addr, data),
            PrgWriteHandler::Mapper235 => self.write_prg_mapper235(addr, data),
            PrgWriteHandler::Cnrom => self.write_prg_cnrom(addr, data),
            PrgWriteHandler::Cprom => self.write_prg_cprom(addr, data),
            PrgWriteHandler::Bnrom => self.write_prg_bnrom(addr, data),
            PrgWriteHandler::Mapper46Inner => self.write_prg_mapper46_inner(addr, data),
            PrgWriteHandler::Mapper191 => self.write_prg_mapper191(addr, data),
            PrgWriteHandler::Mmc3 => self.write_prg_mmc3(addr, data),
            PrgWriteHandler::Mapper12 => self.write_prg_mapper12(addr, data),
            PrgWriteHandler::Mapper44 => self.write_prg_mapper44(addr, data),
            PrgWriteHandler::Mapper48 => self.write_prg_mapper48(addr, data),
            PrgWriteHandler::Mapper114 => self.write_prg_mapper114(addr, data),
            PrgWriteHandler::Mapper123 => self.write_prg_mapper123(addr, data),
            PrgWriteHandler::Mapper250 => self.write_prg_mapper250(addr, data),
            PrgWriteHandler::Mapper57 => self.write_prg_mapper57(addr, data),
            PrgWriteHandler::Mapper59 => self.write_prg_mapper59(addr),
            PrgWriteHandler::Mapper61 => self.write_prg_mapper61(addr),
            PrgWriteHandler::Mapper63 => self.write_prg_mapper63(addr),
            PrgWriteHandler::Mapper137 => self.write_prg_mapper137(addr, data),
            PrgWriteHandler::Mapper142 => self.write_prg_mapper142(addr, data),
            PrgWriteHandler::Mapper150 => self.write_prg_mapper150(addr, data),
            PrgWriteHandler::Mapper58 => self.write_prg_mapper58(addr),
            PrgWriteHandler::Mapper65 => self.write_prg_mapper65(addr, data),
            PrgWriteHandler::Sunsoft3 => self.write_prg_sunsoft3(addr, data),
            PrgWriteHandler::Mapper72_92 => self.write_prg_mapper72_92(addr, data),
            PrgWriteHandler::Sunsoft4 => self.write_prg_sunsoft4(addr, data),
            PrgWriteHandler::Vrc1 => self.write_prg_vrc1(addr, data),
            PrgWriteHandler::Namco108 => self.write_prg_namco108(addr, data),
            PrgWriteHandler::Axrom => self.write_prg_axrom(addr, data),
            PrgWriteHandler::Mapper77 => self.write_prg_mapper77(addr, data),
            PrgWriteHandler::Mapper200 => self.write_prg_mapper200(addr),
            PrgWriteHandler::Mapper201 => self.write_prg_mapper201(addr),
            PrgWriteHandler::Mapper202 => self.write_prg_mapper202(addr),
            PrgWriteHandler::Mapper203 => self.write_prg_mapper203(addr, data),
            PrgWriteHandler::Mapper212 => self.write_prg_mapper212(addr),
            PrgWriteHandler::Mapper226 => self.write_prg_mapper226(addr, data),
            PrgWriteHandler::Mapper228 => self.write_prg_mapper228(addr, data),
            PrgWriteHandler::Mapper229 => self.write_prg_mapper229(addr),
            PrgWriteHandler::Mapper242 => self.write_prg_mapper242(addr),
            PrgWriteHandler::Mapper243 => self.write_prg_mapper243(addr, data),
            PrgWriteHandler::Mapper241 => self.write_prg_mapper241(addr, data),
            PrgWriteHandler::Mapper79_146 => self.write_prg_mapper79_146(addr, data),
            PrgWriteHandler::Mapper133 => self.write_prg_mapper133(addr, data),
            PrgWriteHandler::Mapper113 => self.write_prg_mapper113(addr, data),
            PrgWriteHandler::Mapper144 => self.write_prg_mapper144(addr, data),
            PrgWriteHandler::Mapper145 => self.write_prg_mapper145(addr, data),
            PrgWriteHandler::ColorDreams => self.write_prg_color_dreams(addr, data),
            PrgWriteHandler::Mapper189 => self.write_prg_mapper189(addr, data),
            PrgWriteHandler::Mapper89 => self.write_prg_mapper89(addr, data),
            PrgWriteHandler::Mapper93 => self.write_prg_mapper93(addr, data),
            PrgWriteHandler::Mapper70 => self.write_prg_mapper70(addr, data),
            PrgWriteHandler::Camerica => self.write_prg_camerica(addr, data),
            PrgWriteHandler::Mapper81 => self.write_prg_mapper81(addr),
            PrgWriteHandler::Mapper97 => self.write_prg_mapper97(addr, data),
            PrgWriteHandler::Mapper103 => self.write_prg_mapper103(addr, data),
            PrgWriteHandler::Mapper78 => self.write_prg_mapper78(addr, data),
            PrgWriteHandler::Mapper86 => self.write_prg_mapper86(addr, data),
            PrgWriteHandler::Mapper94 => self.write_prg_mapper94(addr, data),
            PrgWriteHandler::Mapper107 => self.write_prg_mapper107(addr, data),
            PrgWriteHandler::Mapper147 => self.write_prg_mapper147(addr, data),
            PrgWriteHandler::Mapper148 => self.write_prg_mapper148(addr, data),
            PrgWriteHandler::Mapper152 => self.write_prg_mapper152(addr, data),
            PrgWriteHandler::UxromInverted => self.write_prg_uxrom_inverted(addr, data),
            PrgWriteHandler::Mapper240 => self.write_prg_mapper240(addr, data),
            PrgWriteHandler::Mmc2 => self.write_prg_mmc2(addr, data),
            PrgWriteHandler::Bandai => self.write_prg_bandai(addr, data),
            PrgWriteHandler::Gxrom => self.write_prg_gxrom(addr, data),
            PrgWriteHandler::Fme7 => self.write_prg_fme7(addr, data),
            PrgWriteHandler::Mapper87 => self.write_prg_mapper87(addr, data),
        }
    }

    fn prg_write_handler(&self) -> PrgWriteHandler {
        match self.mapper {
            0 | 60 | 80 => PrgWriteHandler::None,
            210 => PrgWriteHandler::Mapper210,
            21 => PrgWriteHandler::Mapper21,
            22 => PrgWriteHandler::Mapper22,
            23 => PrgWriteHandler::Mapper23,
            _ if self.uses_vrc6() => PrgWriteHandler::Vrc6,
            _ if self.uses_vrc7() => PrgWriteHandler::Vrc7,
            25 => PrgWriteHandler::Mapper25,
            18 => PrgWriteHandler::Mapper18,
            _ if self.uses_namco163() => PrgWriteHandler::Namco163,
            _ if self.uses_mmc5() => PrgWriteHandler::Mmc5,
            64 => PrgWriteHandler::Mapper64,
            32 => PrgWriteHandler::Mapper32,
            40 => PrgWriteHandler::Mapper40,
            42 => PrgWriteHandler::Mapper42,
            43 => PrgWriteHandler::Mapper43,
            1 => PrgWriteHandler::Mmc1,
            50 => PrgWriteHandler::Mapper50,
            73 => PrgWriteHandler::Vrc3,
            208 => PrgWriteHandler::Mapper208,
            15 => PrgWriteHandler::Mapper15,
            33 => PrgWriteHandler::TaitoTc0190,
            221 => PrgWriteHandler::Mapper221,
            2 => PrgWriteHandler::Uxrom,
            225 | 255 => PrgWriteHandler::Mapper225,
            230 => PrgWriteHandler::Mapper230,
            227 => PrgWriteHandler::Mapper227,
            231 => PrgWriteHandler::Mapper231,
            236 => PrgWriteHandler::Mapper236,
            41 => PrgWriteHandler::Mapper41,
            232 => PrgWriteHandler::Mapper232,
            233 => PrgWriteHandler::Mapper233,
            234 => PrgWriteHandler::Mapper234,
            235 => PrgWriteHandler::Mapper235,
            3 | 185 => PrgWriteHandler::Cnrom,
            13 => PrgWriteHandler::Cprom,
            34 if self.mappers.simple.mapper34_nina001 => PrgWriteHandler::None,
            34 => PrgWriteHandler::Bnrom,
            46 => PrgWriteHandler::Mapper46Inner,
            191 => PrgWriteHandler::Mapper191,
            4 | 37 | 47 | 74 | 115 | 118 | 119 | 192 | 194 | 195 | 205 | 245 | 248 => {
                PrgWriteHandler::Mmc3
            }
            12 => PrgWriteHandler::Mapper12,
            44 => PrgWriteHandler::Mapper44,
            48 => PrgWriteHandler::Mapper48,
            114 | 182 => PrgWriteHandler::Mapper114,
            123 => PrgWriteHandler::Mapper123,
            250 => PrgWriteHandler::Mapper250,
            57 => PrgWriteHandler::Mapper57,
            59 => PrgWriteHandler::Mapper59,
            61 => PrgWriteHandler::Mapper61,
            63 => PrgWriteHandler::Mapper63,
            137 => PrgWriteHandler::Mapper137,
            142 => PrgWriteHandler::Mapper142,
            150 => PrgWriteHandler::Mapper150,
            58 | 213 => PrgWriteHandler::Mapper58,
            65 => PrgWriteHandler::Mapper65,
            67 => PrgWriteHandler::Sunsoft3,
            72 | 92 => PrgWriteHandler::Mapper72_92,
            68 => PrgWriteHandler::Sunsoft4,
            _ if self.uses_vrc1() => PrgWriteHandler::Vrc1,
            _ if self.uses_namco108() => PrgWriteHandler::Namco108,
            7 => PrgWriteHandler::Axrom,
            77 => PrgWriteHandler::Mapper77,
            200 => PrgWriteHandler::Mapper200,
            201 => PrgWriteHandler::Mapper201,
            202 => PrgWriteHandler::Mapper202,
            203 => PrgWriteHandler::Mapper203,
            212 => PrgWriteHandler::Mapper212,
            226 => PrgWriteHandler::Mapper226,
            228 => PrgWriteHandler::Mapper228,
            229 => PrgWriteHandler::Mapper229,
            242 => PrgWriteHandler::Mapper242,
            243 => PrgWriteHandler::Mapper243,
            241 => PrgWriteHandler::Mapper241,
            79 | 146 => PrgWriteHandler::Mapper79_146,
            133 => PrgWriteHandler::Mapper133,
            113 => PrgWriteHandler::Mapper113,
            144 => PrgWriteHandler::Mapper144,
            145 => PrgWriteHandler::Mapper145,
            11 => PrgWriteHandler::ColorDreams,
            189 => PrgWriteHandler::Mapper189,
            89 => PrgWriteHandler::Mapper89,
            93 => PrgWriteHandler::Mapper93,
            70 => PrgWriteHandler::Mapper70,
            71 => PrgWriteHandler::Camerica,
            81 => PrgWriteHandler::Mapper81,
            97 => PrgWriteHandler::Mapper97,
            103 => PrgWriteHandler::Mapper103,
            78 => PrgWriteHandler::Mapper78,
            86 => PrgWriteHandler::Mapper86,
            94 => PrgWriteHandler::Mapper94,
            107 => PrgWriteHandler::Mapper107,
            147 => PrgWriteHandler::Mapper147,
            148 => PrgWriteHandler::Mapper148,
            152 => PrgWriteHandler::Mapper152,
            180 => PrgWriteHandler::UxromInverted,
            240 => PrgWriteHandler::Mapper240,
            _ if self.uses_mmc2_latches() => PrgWriteHandler::Mmc2,
            _ if self.uses_bandai_fcg() => PrgWriteHandler::Bandai,
            66 => PrgWriteHandler::Gxrom,
            _ if self.uses_fme7() => PrgWriteHandler::Fme7,
            87 => PrgWriteHandler::Mapper87,
            _ => PrgWriteHandler::None,
        }
    }
}
