use super::super::types::SaveState;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub(in crate::save_state) struct LegacySaveState {
    pub(in crate::save_state) cpu_a: u8,
    pub(in crate::save_state) cpu_x: u8,
    pub(in crate::save_state) cpu_y: u8,
    pub(in crate::save_state) cpu_pc: u16,
    pub(in crate::save_state) cpu_sp: u8,
    pub(in crate::save_state) cpu_status: u8,
    pub(in crate::save_state) cpu_cycles: u64,
    pub(in crate::save_state) ppu_control: u8,
    pub(in crate::save_state) ppu_mask: u8,
    pub(in crate::save_state) ppu_status: u8,
    pub(in crate::save_state) ppu_oam_addr: u8,
    pub(in crate::save_state) ppu_scroll_x: u8,
    pub(in crate::save_state) ppu_scroll_y: u8,
    pub(in crate::save_state) ppu_addr: u16,
    pub(in crate::save_state) ppu_data_buffer: u8,
    pub(in crate::save_state) ppu_w: bool,
    pub(in crate::save_state) ppu_t: u16,
    pub(in crate::save_state) ppu_v: u16,
    pub(in crate::save_state) ppu_x: u8,
    pub(in crate::save_state) ppu_scanline: i16,
    pub(in crate::save_state) ppu_cycle: u16,
    pub(in crate::save_state) ppu_frame: u64,
    pub(in crate::save_state) ppu_palette: [u8; 32],
    pub(in crate::save_state) ppu_nametable: Vec<u8>,
    pub(in crate::save_state) ppu_oam: Vec<u8>,
    pub(in crate::save_state) ram: Vec<u8>,
    pub(in crate::save_state) cartridge_prg_bank: u8,
    pub(in crate::save_state) cartridge_chr_bank: u8,
    pub(in crate::save_state) apu_frame_counter: u8,
    pub(in crate::save_state) apu_frame_interrupt: bool,
    pub(in crate::save_state) rom_filename: String,
    pub(in crate::save_state) timestamp: u64,
}

impl From<LegacySaveState> for SaveState {
    fn from(legacy: LegacySaveState) -> Self {
        SaveState {
            cpu_a: legacy.cpu_a,
            cpu_x: legacy.cpu_x,
            cpu_y: legacy.cpu_y,
            cpu_pc: legacy.cpu_pc,
            cpu_sp: legacy.cpu_sp,
            cpu_status: legacy.cpu_status,
            cpu_cycles: legacy.cpu_cycles,
            cpu_halted: false,
            ppu_control: legacy.ppu_control,
            ppu_mask: legacy.ppu_mask,
            ppu_status: legacy.ppu_status,
            ppu_oam_addr: legacy.ppu_oam_addr,
            ppu_scroll_x: legacy.ppu_scroll_x,
            ppu_scroll_y: legacy.ppu_scroll_y,
            ppu_addr: legacy.ppu_addr,
            ppu_data_buffer: legacy.ppu_data_buffer,
            ppu_w: legacy.ppu_w,
            ppu_t: legacy.ppu_t,
            ppu_v: legacy.ppu_v,
            ppu_x: legacy.ppu_x,
            ppu_scanline: legacy.ppu_scanline,
            ppu_cycle: legacy.ppu_cycle,
            ppu_frame: legacy.ppu_frame,
            ppu_palette: legacy.ppu_palette,
            ppu_nametable: legacy.ppu_nametable,
            ppu_oam: legacy.ppu_oam,
            ram: legacy.ram,
            cartridge_prg_bank: legacy.cartridge_prg_bank,
            cartridge_chr_bank: legacy.cartridge_chr_bank,
            cartridge_state: None,
            apu_frame_counter: legacy.apu_frame_counter,
            apu_frame_interrupt: legacy.apu_frame_interrupt,
            apu_state: None,
            rom_filename: legacy.rom_filename,
            timestamp: legacy.timestamp,
            bus_dma_cycles: 0,
            bus_dma_in_progress: false,
            bus_dmc_stall_cycles: 0,
            ppu_frame_complete: false,
        }
    }
}
