use super::super::types::SaveState;
use crate::cartridge::{CartridgeState, Mirroring, Mmc1State};
use serde::{Deserialize, Serialize};

/// CartridgeState before mmc2 was added.
#[derive(Serialize, Deserialize)]
pub(in crate::save_state) struct CartridgeStateV1 {
    pub(in crate::save_state) mapper: u8,
    pub(in crate::save_state) mirroring: Mirroring,
    pub(in crate::save_state) prg_bank: u8,
    pub(in crate::save_state) chr_bank: u8,
    pub(in crate::save_state) prg_ram: Vec<u8>,
    pub(in crate::save_state) chr_ram: Vec<u8>,
    pub(in crate::save_state) has_valid_save_data: bool,
    pub(in crate::save_state) mmc1: Option<Mmc1State>,
}

/// SaveState before mmc2 was added to CartridgeState.
#[derive(Serialize, Deserialize)]
pub(in crate::save_state) struct SaveStateV1 {
    pub(in crate::save_state) cpu_a: u8,
    pub(in crate::save_state) cpu_x: u8,
    pub(in crate::save_state) cpu_y: u8,
    pub(in crate::save_state) cpu_pc: u16,
    pub(in crate::save_state) cpu_sp: u8,
    pub(in crate::save_state) cpu_status: u8,
    pub(in crate::save_state) cpu_cycles: u64,
    pub(in crate::save_state) ppu_control: u8,
    pub(in crate::save_state) ppu_mask: u8,
    pub(in crate::save_state) ppu_status: u8,
    pub(in crate::save_state) ppu_oam_addr: u8,
    pub(in crate::save_state) ppu_scroll_x: u8,
    pub(in crate::save_state) ppu_scroll_y: u8,
    pub(in crate::save_state) ppu_addr: u16,
    pub(in crate::save_state) ppu_data_buffer: u8,
    pub(in crate::save_state) ppu_w: bool,
    pub(in crate::save_state) ppu_t: u16,
    pub(in crate::save_state) ppu_v: u16,
    pub(in crate::save_state) ppu_x: u8,
    pub(in crate::save_state) ppu_scanline: i16,
    pub(in crate::save_state) ppu_cycle: u16,
    pub(in crate::save_state) ppu_frame: u64,
    pub(in crate::save_state) ppu_palette: [u8; 32],
    pub(in crate::save_state) ppu_nametable: Vec<u8>,
    pub(in crate::save_state) ppu_oam: Vec<u8>,
    pub(in crate::save_state) ram: Vec<u8>,
    pub(in crate::save_state) cartridge_prg_bank: u8,
    pub(in crate::save_state) cartridge_chr_bank: u8,
    pub(in crate::save_state) cartridge_state: Option<CartridgeStateV1>,
    pub(in crate::save_state) apu_frame_counter: u8,
    pub(in crate::save_state) apu_frame_interrupt: bool,
    pub(in crate::save_state) rom_filename: String,
    pub(in crate::save_state) timestamp: u64,
}

impl From<SaveStateV1> for SaveState {
    fn from(v1: SaveStateV1) -> Self {
        SaveState {
            cpu_a: v1.cpu_a,
            cpu_x: v1.cpu_x,
            cpu_y: v1.cpu_y,
            cpu_pc: v1.cpu_pc,
            cpu_sp: v1.cpu_sp,
            cpu_status: v1.cpu_status,
            cpu_cycles: v1.cpu_cycles,
            cpu_halted: false,
            ppu_control: v1.ppu_control,
            ppu_mask: v1.ppu_mask,
            ppu_status: v1.ppu_status,
            ppu_oam_addr: v1.ppu_oam_addr,
            ppu_scroll_x: v1.ppu_scroll_x,
            ppu_scroll_y: v1.ppu_scroll_y,
            ppu_addr: v1.ppu_addr,
            ppu_data_buffer: v1.ppu_data_buffer,
            ppu_w: v1.ppu_w,
            ppu_t: v1.ppu_t,
            ppu_v: v1.ppu_v,
            ppu_x: v1.ppu_x,
            ppu_scanline: v1.ppu_scanline,
            ppu_cycle: v1.ppu_cycle,
            ppu_frame: v1.ppu_frame,
            ppu_palette: v1.ppu_palette,
            ppu_nametable: v1.ppu_nametable,
            ppu_oam: v1.ppu_oam,
            ram: v1.ram,
            cartridge_prg_bank: v1.cartridge_prg_bank,
            cartridge_chr_bank: v1.cartridge_chr_bank,
            cartridge_state: v1.cartridge_state.map(CartridgeState::from),
            apu_frame_counter: v1.apu_frame_counter,
            apu_frame_interrupt: v1.apu_frame_interrupt,
            apu_state: None,
            rom_filename: v1.rom_filename,
            timestamp: v1.timestamp,
            bus_dma_cycles: 0,
            bus_dma_in_progress: false,
            bus_dmc_stall_cycles: 0,
            ppu_frame_complete: false,
        }
    }
}

impl From<CartridgeStateV1> for CartridgeState {
    fn from(v1: CartridgeStateV1) -> Self {
        CartridgeState {
            mapper: u16::from(v1.mapper),
            mirroring: v1.mirroring,
            prg_bank: v1.prg_bank,
            chr_bank: v1.chr_bank,
            prg_ram: v1.prg_ram,
            chr_ram: v1.chr_ram,
            has_valid_save_data: v1.has_valid_save_data,
            mmc1: v1.mmc1,
            mmc2: None,
            mmc3: None,
            mmc5: None,
            namco163: None,
            fme7: None,
            bandai_fcg: None,
            mapper34: None,
            mapper93: None,
            mapper184: None,
            vrc1: None,
            vrc2_vrc4: None,
            mapper15: None,
            mapper72: None,
            mapper58: None,
            mapper59: None,
            mapper60: None,
            mapper225: None,
            mapper232: None,
            mapper234: None,
            mapper235: None,
            mapper202: None,
            mapper212: None,
            mapper226: None,
            mapper230: None,
            mapper228: None,
            mapper242: None,
            mapper243: None,
            mapper221: None,
            mapper191: None,
            mapper195: None,
            mapper208: None,
            mapper189: None,
            mapper236: None,
            mapper227: None,
            mapper246: None,
            sunsoft4: None,
            taito_tc0190: None,
            taito_x1005: None,
            taito_x1017: None,
            mapper233: None,
            mapper41: None,
            mapper40: None,
            mapper42: None,
            mapper50: None,
            irem_g101: None,
            vrc3: None,
            mapper43: None,
            irem_h3001: None,
            mapper103: None,
            mapper37: None,
            mapper44: None,
            mapper47: None,
            mapper12: None,
            mapper114: None,
            mapper123: None,
            mapper115: None,
            mapper205: None,
            mapper61: None,
            mapper185: None,
            sunsoft3: None,
            mapper63: None,
            mapper137: None,
            mapper142: None,
            mapper150: None,
            mapper18: None,
            mapper210: None,
            vrc6: None,
            vrc7: None,
        }
    }
}
