use super::super::types::SaveState;
use super::CartridgeStateU8Mapper;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub(in crate::save_state) struct SaveStateV2 {
    pub(in crate::save_state) cpu_a: u8,
    pub(in crate::save_state) cpu_x: u8,
    pub(in crate::save_state) cpu_y: u8,
    pub(in crate::save_state) cpu_pc: u16,
    pub(in crate::save_state) cpu_sp: u8,
    pub(in crate::save_state) cpu_status: u8,
    pub(in crate::save_state) cpu_cycles: u64,
    pub(in crate::save_state) ppu_control: u8,
    pub(in crate::save_state) ppu_mask: u8,
    pub(in crate::save_state) ppu_status: u8,
    pub(in crate::save_state) ppu_oam_addr: u8,
    pub(in crate::save_state) ppu_scroll_x: u8,
    pub(in crate::save_state) ppu_scroll_y: u8,
    pub(in crate::save_state) ppu_addr: u16,
    pub(in crate::save_state) ppu_data_buffer: u8,
    pub(in crate::save_state) ppu_w: bool,
    pub(in crate::save_state) ppu_t: u16,
    pub(in crate::save_state) ppu_v: u16,
    pub(in crate::save_state) ppu_x: u8,
    pub(in crate::save_state) ppu_scanline: i16,
    pub(in crate::save_state) ppu_cycle: u16,
    pub(in crate::save_state) ppu_frame: u64,
    pub(in crate::save_state) ppu_palette: [u8; 32],
    pub(in crate::save_state) ppu_nametable: Vec<u8>,
    pub(in crate::save_state) ppu_oam: Vec<u8>,
    pub(in crate::save_state) ram: Vec<u8>,
    pub(in crate::save_state) cartridge_prg_bank: u8,
    pub(in crate::save_state) cartridge_chr_bank: u8,
    pub(in crate::save_state) cartridge_state: Option<CartridgeStateU8Mapper>,
    pub(in crate::save_state) apu_frame_counter: u8,
    pub(in crate::save_state) apu_frame_interrupt: bool,
    pub(in crate::save_state) rom_filename: String,
    pub(in crate::save_state) timestamp: u64,
}

impl From<SaveStateV2> for SaveState {
    fn from(v2: SaveStateV2) -> Self {
        SaveState {
            cpu_a: v2.cpu_a,
            cpu_x: v2.cpu_x,
            cpu_y: v2.cpu_y,
            cpu_pc: v2.cpu_pc,
            cpu_sp: v2.cpu_sp,
            cpu_status: v2.cpu_status,
            cpu_cycles: v2.cpu_cycles,
            cpu_halted: false,
            ppu_control: v2.ppu_control,
            ppu_mask: v2.ppu_mask,
            ppu_status: v2.ppu_status,
            ppu_oam_addr: v2.ppu_oam_addr,
            ppu_scroll_x: v2.ppu_scroll_x,
            ppu_scroll_y: v2.ppu_scroll_y,
            ppu_addr: v2.ppu_addr,
            ppu_data_buffer: v2.ppu_data_buffer,
            ppu_w: v2.ppu_w,
            ppu_t: v2.ppu_t,
            ppu_v: v2.ppu_v,
            ppu_x: v2.ppu_x,
            ppu_scanline: v2.ppu_scanline,
            ppu_cycle: v2.ppu_cycle,
            ppu_frame: v2.ppu_frame,
            ppu_palette: v2.ppu_palette,
            ppu_nametable: v2.ppu_nametable,
            ppu_oam: v2.ppu_oam,
            ram: v2.ram,
            cartridge_prg_bank: v2.cartridge_prg_bank,
            cartridge_chr_bank: v2.cartridge_chr_bank,
            cartridge_state: v2.cartridge_state.map(Into::into),
            apu_frame_counter: v2.apu_frame_counter,
            apu_frame_interrupt: v2.apu_frame_interrupt,
            apu_state: None,
            rom_filename: v2.rom_filename,
            timestamp: v2.timestamp,
            bus_dma_cycles: 0,
            bus_dma_in_progress: false,
            bus_dmc_stall_cycles: 0,
            ppu_frame_complete: false,
        }
    }
}
