pub(in crate::apu) struct PulseChannel {
    pub(in crate::apu) duty: u8,
    pub(in crate::apu) length_counter: u8,
    pub(in crate::apu) envelope_divider: u8,
    pub(in crate::apu) envelope_decay: u8,
    pub(in crate::apu) envelope_disable: bool,
    pub(in crate::apu) envelope_start: bool,
    pub(in crate::apu) volume: u8,
    pub(in crate::apu) sweep_enabled: bool,
    pub(in crate::apu) sweep_period: u8,
    pub(in crate::apu) sweep_negate: bool,
    pub(in crate::apu) sweep_shift: u8,
    pub(in crate::apu) sweep_reload: bool,
    pub(in crate::apu) sweep_divider: u8,
    pub(in crate::apu) timer: u16,
    pub(in crate::apu) timer_reload: u16,
    pub(in crate::apu) duty_counter: u8,
    pub(in crate::apu) length_enabled: bool,
    pub(in crate::apu) is_pulse1: bool,
}

pub(in crate::apu) struct TriangleChannel {
    pub(in crate::apu) linear_counter: u8,
    pub(in crate::apu) linear_reload: u8,
    pub(in crate::apu) linear_control: bool,
    pub(in crate::apu) linear_reload_flag: bool,
    pub(in crate::apu) length_counter: u8,
    pub(in crate::apu) timer: u16,
    pub(in crate::apu) timer_reload: u16,
    pub(in crate::apu) sequence_counter: u8,
    pub(in crate::apu) length_enabled: bool,
}

pub(in crate::apu) struct NoiseChannel {
    pub(in crate::apu) length_counter: u8,
    pub(in crate::apu) envelope_divider: u8,
    pub(in crate::apu) envelope_decay: u8,
    pub(in crate::apu) envelope_disable: bool,
    pub(in crate::apu) envelope_start: bool,
    pub(in crate::apu) volume: u8,
    pub(in crate::apu) mode: bool,
    pub(in crate::apu) timer: u16,
    pub(in crate::apu) timer_reload: u16,
    pub(in crate::apu) shift_register: u16,
    pub(in crate::apu) length_enabled: bool,
}

pub(in crate::apu) struct DmcChannel {
    pub(in crate::apu) irq_enabled: bool,
    pub(in crate::apu) irq_pending: bool,
    pub(in crate::apu) loop_flag: bool,
    pub(in crate::apu) timer: u16,
    pub(in crate::apu) timer_reload: u16,
    pub(in crate::apu) output_level: u8,
    pub(in crate::apu) sample_address: u16,
    pub(in crate::apu) sample_length: u16,
    pub(in crate::apu) current_address: u16,
    pub(in crate::apu) bytes_remaining: u16,
    pub(in crate::apu) sample_buffer: Option<u8>,
    pub(in crate::apu) shift_register: u8,
    pub(in crate::apu) bits_remaining: u8,
    pub(in crate::apu) silence: bool,
    pub(in crate::apu) dma_delay: u8,
    pub(in crate::apu) pending_dma_stall_cycles: u8,
}
